services:
  mysql:
    image: mysql:8.0
    container_name: assignment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: assignment
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-psecret",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  migrate:
    image: migrate/migrate
    container_name: assignment-migrate
    restart: on-failure:3
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "mysql://root:secret@tcp(mysql:3306)/assignment",
        "up",
      ]
    depends_on:
      mysql:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assignment-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
      - LOG_FORMAT=console
      - DATABASE_URL=root:secret@tcp(mysql:3306)/assignment?parseTime=true
      - JWT_SECRET=secret
      - JWT_ISSUER=linebk-backend-assignment
      - JWT_ACCESS_EXPIRY_SECONDS=43200
      - JWT_REFRESH_EXPIRY_SECONDS=86400
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  mysql-data:
