// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/WuttinunSkywalker/linebk-backend-assignment/internal/api/account"
	mock "github.com/stretchr/testify/mock"
)

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

type AccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepository) EXPECT() *AccountRepository_Expecter {
	return &AccountRepository_Expecter{mock: &_m.Mock}
}

// CountAccountsByUserID provides a mock function for the type AccountRepository
func (_mock *AccountRepository) CountAccountsByUserID(userID string) (int, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CountAccountsByUserID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_CountAccountsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAccountsByUserID'
type AccountRepository_CountAccountsByUserID_Call struct {
	*mock.Call
}

// CountAccountsByUserID is a helper method to define mock.On call
//   - userID string
func (_e *AccountRepository_Expecter) CountAccountsByUserID(userID interface{}) *AccountRepository_CountAccountsByUserID_Call {
	return &AccountRepository_CountAccountsByUserID_Call{Call: _e.mock.On("CountAccountsByUserID", userID)}
}

func (_c *AccountRepository_CountAccountsByUserID_Call) Run(run func(userID string)) *AccountRepository_CountAccountsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AccountRepository_CountAccountsByUserID_Call) Return(n int, err error) *AccountRepository_CountAccountsByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *AccountRepository_CountAccountsByUserID_Call) RunAndReturn(run func(userID string) (int, error)) *AccountRepository_CountAccountsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountsByUserID provides a mock function for the type AccountRepository
func (_mock *AccountRepository) GetAccountsByUserID(userID string, limit int, offset int) ([]*account.Account, error) {
	ret := _mock.Called(userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsByUserID")
	}

	var r0 []*account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]*account.Account, error)); ok {
		return returnFunc(userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []*account.Account); ok {
		r0 = returnFunc(userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_GetAccountsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsByUserID'
type AccountRepository_GetAccountsByUserID_Call struct {
	*mock.Call
}

// GetAccountsByUserID is a helper method to define mock.On call
//   - userID string
//   - limit int
//   - offset int
func (_e *AccountRepository_Expecter) GetAccountsByUserID(userID interface{}, limit interface{}, offset interface{}) *AccountRepository_GetAccountsByUserID_Call {
	return &AccountRepository_GetAccountsByUserID_Call{Call: _e.mock.On("GetAccountsByUserID", userID, limit, offset)}
}

func (_c *AccountRepository_GetAccountsByUserID_Call) Run(run func(userID string, limit int, offset int)) *AccountRepository_GetAccountsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AccountRepository_GetAccountsByUserID_Call) Return(accounts []*account.Account, err error) *AccountRepository_GetAccountsByUserID_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *AccountRepository_GetAccountsByUserID_Call) RunAndReturn(run func(userID string, limit int, offset int) ([]*account.Account, error)) *AccountRepository_GetAccountsByUserID_Call {
	_c.Call.Return(run)
	return _c
}
