// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/WuttinunSkywalker/linebk-backend-assignment/internal/api/transaction"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionUsecase creates a new instance of TransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionUsecase {
	mock := &TransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

type TransactionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionUsecase) EXPECT() *TransactionUsecase_Expecter {
	return &TransactionUsecase_Expecter{mock: &_m.Mock}
}

// GetTransactionsByUserID provides a mock function for the type TransactionUsecase
func (_mock *TransactionUsecase) GetTransactionsByUserID(userID string, limit int, offset int) ([]*transaction.TransactionResponse, int, error) {
	ret := _mock.Called(userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByUserID")
	}

	var r0 []*transaction.TransactionResponse
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]*transaction.TransactionResponse, int, error)); ok {
		return returnFunc(userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []*transaction.TransactionResponse); ok {
		r0 = returnFunc(userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*transaction.TransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) int); ok {
		r1 = returnFunc(userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = returnFunc(userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TransactionUsecase_GetTransactionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionsByUserID'
type TransactionUsecase_GetTransactionsByUserID_Call struct {
	*mock.Call
}

// GetTransactionsByUserID is a helper method to define mock.On call
//   - userID string
//   - limit int
//   - offset int
func (_e *TransactionUsecase_Expecter) GetTransactionsByUserID(userID interface{}, limit interface{}, offset interface{}) *TransactionUsecase_GetTransactionsByUserID_Call {
	return &TransactionUsecase_GetTransactionsByUserID_Call{Call: _e.mock.On("GetTransactionsByUserID", userID, limit, offset)}
}

func (_c *TransactionUsecase_GetTransactionsByUserID_Call) Run(run func(userID string, limit int, offset int)) *TransactionUsecase_GetTransactionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionUsecase_GetTransactionsByUserID_Call) Return(transactionResponses []*transaction.TransactionResponse, n int, err error) *TransactionUsecase_GetTransactionsByUserID_Call {
	_c.Call.Return(transactionResponses, n, err)
	return _c
}

func (_c *TransactionUsecase_GetTransactionsByUserID_Call) RunAndReturn(run func(userID string, limit int, offset int) ([]*transaction.TransactionResponse, int, error)) *TransactionUsecase_GetTransactionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}
