// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionHandler creates a new instance of TransactionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionHandler {
	mock := &TransactionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionHandler is an autogenerated mock type for the TransactionHandler type
type TransactionHandler struct {
	mock.Mock
}

type TransactionHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionHandler) EXPECT() *TransactionHandler_Expecter {
	return &TransactionHandler_Expecter{mock: &_m.Mock}
}

// GetMyTransactions provides a mock function for the type TransactionHandler
func (_mock *TransactionHandler) GetMyTransactions(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// TransactionHandler_GetMyTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyTransactions'
type TransactionHandler_GetMyTransactions_Call struct {
	*mock.Call
}

// GetMyTransactions is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *TransactionHandler_Expecter) GetMyTransactions(ctx interface{}) *TransactionHandler_GetMyTransactions_Call {
	return &TransactionHandler_GetMyTransactions_Call{Call: _e.mock.On("GetMyTransactions", ctx)}
}

func (_c *TransactionHandler_GetMyTransactions_Call) Run(run func(ctx *gin.Context)) *TransactionHandler_GetMyTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TransactionHandler_GetMyTransactions_Call) Return() *TransactionHandler_GetMyTransactions_Call {
	_c.Call.Return()
	return _c
}

func (_c *TransactionHandler_GetMyTransactions_Call) RunAndReturn(run func(ctx *gin.Context)) *TransactionHandler_GetMyTransactions_Call {
	_c.Run(run)
	return _c
}
