// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

type AuthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthHandler) EXPECT() *AuthHandler_Expecter {
	return &AuthHandler_Expecter{mock: &_m.Mock}
}

// LoginWithPin provides a mock function for the type AuthHandler
func (_mock *AuthHandler) LoginWithPin(c *gin.Context) {
	_mock.Called(c)
	return
}

// AuthHandler_LoginWithPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithPin'
type AuthHandler_LoginWithPin_Call struct {
	*mock.Call
}

// LoginWithPin is a helper method to define mock.On call
//   - c *gin.Context
func (_e *AuthHandler_Expecter) LoginWithPin(c interface{}) *AuthHandler_LoginWithPin_Call {
	return &AuthHandler_LoginWithPin_Call{Call: _e.mock.On("LoginWithPin", c)}
}

func (_c *AuthHandler_LoginWithPin_Call) Run(run func(c *gin.Context)) *AuthHandler_LoginWithPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthHandler_LoginWithPin_Call) Return() *AuthHandler_LoginWithPin_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthHandler_LoginWithPin_Call) RunAndReturn(run func(c *gin.Context)) *AuthHandler_LoginWithPin_Call {
	_c.Run(run)
	return _c
}
