// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/WuttinunSkywalker/linebk-backend-assignment/internal/api/banner"
	mock "github.com/stretchr/testify/mock"
)

// NewBannerUsecase creates a new instance of BannerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBannerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BannerUsecase {
	mock := &BannerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BannerUsecase is an autogenerated mock type for the BannerUsecase type
type BannerUsecase struct {
	mock.Mock
}

type BannerUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *BannerUsecase) EXPECT() *BannerUsecase_Expecter {
	return &BannerUsecase_Expecter{mock: &_m.Mock}
}

// GetBannersByUserID provides a mock function for the type BannerUsecase
func (_mock *BannerUsecase) GetBannersByUserID(userID string, limit int, offset int) ([]*banner.BannerResponse, int, error) {
	ret := _mock.Called(userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBannersByUserID")
	}

	var r0 []*banner.BannerResponse
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]*banner.BannerResponse, int, error)); ok {
		return returnFunc(userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []*banner.BannerResponse); ok {
		r0 = returnFunc(userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*banner.BannerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) int); ok {
		r1 = returnFunc(userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = returnFunc(userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BannerUsecase_GetBannersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBannersByUserID'
type BannerUsecase_GetBannersByUserID_Call struct {
	*mock.Call
}

// GetBannersByUserID is a helper method to define mock.On call
//   - userID string
//   - limit int
//   - offset int
func (_e *BannerUsecase_Expecter) GetBannersByUserID(userID interface{}, limit interface{}, offset interface{}) *BannerUsecase_GetBannersByUserID_Call {
	return &BannerUsecase_GetBannersByUserID_Call{Call: _e.mock.On("GetBannersByUserID", userID, limit, offset)}
}

func (_c *BannerUsecase_GetBannersByUserID_Call) Run(run func(userID string, limit int, offset int)) *BannerUsecase_GetBannersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BannerUsecase_GetBannersByUserID_Call) Return(bannerResponses []*banner.BannerResponse, n int, err error) *BannerUsecase_GetBannersByUserID_Call {
	_c.Call.Return(bannerResponses, n, err)
	return _c
}

func (_c *BannerUsecase_GetBannersByUserID_Call) RunAndReturn(run func(userID string, limit int, offset int) ([]*banner.BannerResponse, int, error)) *BannerUsecase_GetBannersByUserID_Call {
	_c.Call.Return(run)
	return _c
}
