// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewDebitHandler creates a new instance of DebitHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDebitHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *DebitHandler {
	mock := &DebitHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DebitHandler is an autogenerated mock type for the DebitHandler type
type DebitHandler struct {
	mock.Mock
}

type DebitHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *DebitHandler) EXPECT() *DebitHandler_Expecter {
	return &DebitHandler_Expecter{mock: &_m.Mock}
}

// GetMyDebitCards provides a mock function for the type DebitHandler
func (_mock *DebitHandler) GetMyDebitCards(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// DebitHandler_GetMyDebitCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyDebitCards'
type DebitHandler_GetMyDebitCards_Call struct {
	*mock.Call
}

// GetMyDebitCards is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *DebitHandler_Expecter) GetMyDebitCards(ctx interface{}) *DebitHandler_GetMyDebitCards_Call {
	return &DebitHandler_GetMyDebitCards_Call{Call: _e.mock.On("GetMyDebitCards", ctx)}
}

func (_c *DebitHandler_GetMyDebitCards_Call) Run(run func(ctx *gin.Context)) *DebitHandler_GetMyDebitCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DebitHandler_GetMyDebitCards_Call) Return() *DebitHandler_GetMyDebitCards_Call {
	_c.Call.Return()
	return _c
}

func (_c *DebitHandler_GetMyDebitCards_Call) RunAndReturn(run func(ctx *gin.Context)) *DebitHandler_GetMyDebitCards_Call {
	_c.Run(run)
	return _c
}
